apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-db-config
data:
  initdb.sql: |
    DROP USER IF EXISTS 'db_user'@'%';
    DROP USER IF EXISTS 'db_user'@'*';
    DROP USER IF EXISTS 'db_user'@'localhost';
    CREATE USER 'db_user'@'%' IDENTIFIED BY 'password';
    DROP DATABASE IF EXISTS ms_architecture_system;
    CREATE DATABASE ms_architecture_system;
    GRANT ALL PRIVILEGES ON ms_architecture_system.* TO 'db_user'@'%';
    USE ms_architecture_system;
    CREATE TABLE user (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL);
    INSERT INTO user (email, password) VALUES ('ju.maciel.ferreira@gmail.com', 'password');