apiVersion: v1
kind: Pod
metadata:
  name: mysql
  # NOTE: Added the following 2 lines:
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql:8.0
      imagePullPolicy: Always
      ports:
        - containerPort: 3306
      envFrom:
        - secretRef:
            name: mysql-db-secret
      volumeMounts:
        - name: mysql-db
          mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: mysql-db
      configMap:
        name: mysql-db-config